#!/bin/sh
set -e

# Partitions
PARTITIONS_INSTALLATION_DEVICE=/dev/sda
PARTITIONS_HOME_PARTITION_SIZE_MB=2048
PARTITIONS_ROOT_PARTITION_SIZE_MB=16384
PARTITIONS_EFI_PARTITION_SIZE_MB=512

echo -n "Checking network connectivity -> "
ping -c 1 -W 3 google.com &> /dev/null || ( echo "ERROR" && exit 1 ) && echo "OK"

timedatectl set-ntp true

FIRST_PARTITION_END=$PARTITIONS_EFI_PARTITION_SIZE_MB
SECOND_PARTITION_END=$(expr $PARTITIONS_EFI_PARTITION_SIZE_MB + $PARTITIONS_ROOT_PARTITION_SIZE_MB)
THRID_PARTITION_END=$(expr $SECOND_PARTITION_END + $PARTITIONS_HOME_PARTITION_SIZE_MB)

# create disk partitions
parted --script $PARTITIONS_INSTALLATION_DEVICE \
    mklabel gpt \
    mklabel primary 1MB $FIRST_PARTITION_END \
    mklabel primary $FIRST_PARTITION_END $SECOND_PARTITION_END \
    mklabel primary $SECOND_PARTITION_END $THRID_PARTITION_END;
