#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

( /bin/defaultmon && nitrogen --restore ) &
sxhkd &

# keyboard land
( sleep 3 && \
  setxkbmap lv && \
  xset r rate 300 50 && \
  xmodmap ~/.Xmodmap ) &

cbatticon & # battery tray
nm-applet & # network status applet
#pa-applet & # pulseaudio applet

( blueman-applet && bluetooth-autoconnect -d ) &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & # password prompts for privileged actions

compton --backend glx --paint-on-overlay & # transparency

redshift -O 4200 &

st -c "tmux" -e "tmux" &
( which emojigun && emojigun ) &

# if [ $USER == "work" ]; then
#    ( which aw-qt && aw-qt ) &
#    ( which slack && slack ) &
#    ( which intellij-idea-ultimate-edition && intellij-idea-ultimate-edition ) &
#    ( which datagrip && datagrip ) &
#    ( sleep 4 && which brave && brave ) &
# fi

# if [ $USER == "ilmars" ]; then
#     ( which discord && discord ) &
#     ( sleep 4 && which brave && brave ) &
# fi

( which stretchly && stretchly ) &

( sleep 5 && bluetooth-autoconnect ) & # sometimes the autoconnect doesn't work the first time

xbanish & # hide cursor when typing
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- lock &

# setup x overlay bar for volume and backlight controls
( mkdir -p /tmp/xob && mkfifo /tmp/xob/{backlight,volume} )
( tail -f /tmp/xob/backlight | xob -t 1500 -s backlight ) &
( tail -f /tmp/xob/volume | xob -t 1500 -s volume ) &

( which check_battery && while true; do check_battery; sleep 60; done ) &


while true; do
   xsetroot -name "$( date +"%F %R" )"
   sleep 1m    # Update time every minute
done &

dunst &

exec dwm
