#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

/bin/defaultmon && nitrogen --restore
sxhkd &
pulseaudio &

# keyboard land
( sleep 3 && \
  xset r rate 300 50 && \
  xmodmap ~/.xmodmap && \
  xcape -e 'Mode_switch=Escape' ) &

cbatticon & # battery tray
nm-applet & # network status applet
pa-applet & # pulseaudio applet

( blueman-applet && bluetooth-autoconnect -d ) &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & # password prompts for privileged actions
xfce4-power-manager & # display brightness

compton & # transparency
xautolock -time 10 -locker ~/.install/bin/blurlocklog -corners ---- & # pc locker

redshift -O 4200 &

st -c "tmux" -e "tmux" &
# stretchly &
# emojigun &
# discord &

( sleep 5 && bluetooth-autoconnect ) & # sometimes the autoconnect doesn't work the first time

# cursor land
xbanish & # hide cursor when typing

export _JAVA_AWT_WM_NONREPARENTING=1 # fix for IDEA blank windows

exec dwm
